// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetGallery.Models;

#nullable disable

namespace PetGallery.Migrations
{
    [DbContext(typeof(GalleryContext))]
    [Migration("20260226214423_DogsAndCatsCreation")]
    partial class DogsAndCatsCreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PetGallery.Models.Cats", b =>
                {
                    b.Property<int>("CatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CatId"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CatId");

                    b.ToTable("Cat");

                    b.HasData(
                        new
                        {
                            CatId = 1,
                            Age = 3,
                            Breed = "Persian",
                            Name = "Fluffy"
                        },
                        new
                        {
                            CatId = 2,
                            Age = 5,
                            Breed = "Siamese",
                            Name = "Whiskers"
                        },
                        new
                        {
                            CatId = 3,
                            Age = 2,
                            Breed = "Maine C",
                            Name = "Shadow"
                        });
                });

            modelBuilder.Entity("PetGallery.Models.Dogs", b =>
                {
                    b.Property<int>("DogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DogId"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DogId");

                    b.ToTable("Dog");

                    b.HasData(
                        new
                        {
                            DogId = 1,
                            Age = 4,
                            Breed = "Golden Retriever",
                            Name = "Buddy"
                        },
                        new
                        {
                            DogId = 2,
                            Age = 6,
                            Breed = "Labrador Retriever",
                            Name = "Max"
                        },
                        new
                        {
                            DogId = 3,
                            Age = 3,
                            Breed = "German Shepherd",
                            Name = "Bella"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
